[package]
name = "rust-kata"
version = "0.1.0"
authors = ["James Greenleaf <james@greenle.af>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
